spring:
  application:
    name: WorkoutTracker
  security:
    user:
      name: USER001
      password: 122345

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: ${DB_NAME:workout_tracker}
    schema: public
    username: ${DB_USERNAME:santim100}
    password: ${DB_PASSWORD:santiagomac}






