spring:
  application:
    name: WorkoutTracker
  security:
    user:
      name: USER001
      password: 122345
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20







