spring:
  application:
    name: WorkoutTracker
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/workout_tracker}
    username: ${DB_USERNAME:santim100}
    password: ${DB_PASSWORD:santiagomac}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect